version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: next-starter-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: next_starter
      POSTGRES_USER: starter_username
      POSTGRES_PASSWORD: starter_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
