name: Playwright Tests
on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request: null
  workflow_dispatch: null

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
      GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
      GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
      GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
      GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm i
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm run e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
